// Assembly Microsoft.Practices.EnterpriseLibrary.Common, Version 3.1.0.0

[assembly: System.Reflection.AssemblyVersion("3.1.0.0")]
[assembly: System.Diagnostics.Debuggable(System.Diagnostics.DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints | System.Diagnostics.DebuggableAttribute.DebuggingModes.Default)]
[assembly: System.Runtime.CompilerServices.CompilationRelaxations(8)]
[assembly: System.Reflection.AssemblyProduct("Microsoft Enterprise Library for .NET")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Microsoft.Practices.EnterpriseLibrary.SqlConfigurationSource.Tests")]
[assembly: System.CLSCompliant(true)]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Microsoft.Practices.EnterpriseLibrary.Logging.Tests")]
[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows=true)]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Microsoft.Practices.EnterpriseLibrary.Common.Tests")]
[assembly: Microsoft.Practices.EnterpriseLibrary.Common.Configuration.Manageability.ConfigurationSectionManageabilityProvider("instrumentationConfiguration", typeof(Microsoft.Practices.EnterpriseLibrary.Common.Configuration.Manageability.InstrumentationConfigurationSectionManageabilityProvider))]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Microsoft.Practices.EnterpriseLibrary.Common.Configuration.Manageability.Design")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("EnterpriseLibrary.Common.Configuration.Manageability.Tests")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Microsoft.Practices.EnterpriseLibrary.Security.Cryptography.Tests")]
[assembly: System.Reflection.AssemblyTitle("Enterprise Library Shared Library")]
[assembly: System.Reflection.AssemblyConfiguration("Release")]
[assembly: System.Management.Instrumentation.Instrumented(@"root\EnterpriseLibrary")]
[assembly: System.Reflection.AssemblyDescription("Enterprise Library Shared Library")]
[assembly: System.Reflection.AssemblyCompany("Microsoft Corporation")]
[assembly: System.Runtime.ConstrainedExecution.ReliabilityContract(System.Runtime.ConstrainedExecution.Consistency.WillNotCorruptState, System.Runtime.ConstrainedExecution.Cer.None)]
[assembly: System.Reflection.AssemblyTrademark("")]
[assembly: System.Reflection.AssemblyCopyright("")]
[assembly: System.Security.Permissions.ReflectionPermission(System.Security.Permissions.SecurityAction.RequestMinimum)]
[assembly: System.Security.Permissions.SecurityPermission(System.Security.Permissions.SecurityAction.RequestMinimum)]

